### ISSUE TITLE
Ricostruzione degli esoni con cutfiller

### ISSUE THREAD

**Issue by rrizzi** [AlgoLab/PIntron-scripts#1]
Lo script python cutfiller può prendere in input:
- (opzioni -p) il file predicted-introns.txt che contiene la lista degli introni predetti da PIntron; il primo e il secondo campo di ogni record sono lo start e l'end dell'introne relative alla genomica in input, il terzo e il quarto campo sono lo start e l'end dell'introne sul cromosoma, il quinto campo è la sua lunghezza;
- (opzione -a) il file out-after-intron-agree.txt che contiene gli allineamenti di PIntron di tutti i reads (spliced e unspliced) rispetto alla genomica in input (qui si trovano solo coordinate relative alla genomica e non rispetto al cromosoma)

e produce in stdout la lista degli esoni ricostruiti; il formato attuale è:
[start] [end] [flag]
dove:
[start] è lo start dell'esone sulla genomica in input (e NON sul cromosoma)
[end] è l'end dell'esone sulla genomica in input (e NON sul cromosoma)
[flag]:
0 se entrambi gli estremi dell'esone sono siti di splicing
1 se solo lo start è un sito di splicing (l'esone è incompleto al 3')
2 se solo l'end è un sito di splicing (l'esone è incompleto al 5')

La prima cosa da modificare sono le coordinate degli esoni devono essere date rispetto al cromosoma (e NON rispetto alla genomica in input).

E' da integrare poi in cutfiller la fase di filtraggio degli introni/esoni poco "affidabili". Il filtraggio deve avvenire sulla base delle coperture degli esoni da parte dei reads, del numero di reads che supportano l'introne e sulla base dei pattern.

**Comment by beretta** [comment]
Realizzato lo script cutfiller2 come da indicazioni.
